-- ============================================================
-- ALEGRE × GOOD HABITS — catalog migration (static → live DB)
-- Migrates every sample product from src/data/coffee.js + src/data/thrift.js
-- and every event from src/data/events.js into Postgres.
--
-- Run AFTER supabase/schema.sql, in your project's SQL Editor.
-- Safe to re-run: products/events upsert on slug; images insert only
-- for products that don't have one yet.
--
-- After this, the data lives in the DB. The app still reads the static
-- files until api.js is switched to Supabase (planned follow-up) —
-- at that point these same slugs/fields are what it will query.
-- ============================================================

-- ============ COFFEE (15) ============
insert into public.products
  (slug, type, category, name, short_desc, description, price, stock,
   brand, size, condition_grade, measurements, options,
   is_available, is_featured, collection)
values
  ('espresso', 'coffee', 'espresso', 'Espresso',
   'Double shot, pulled short and syrupy.',
   'A double ristretto-style shot of our house blend — chocolatey, heavy, and sweet enough to drink bare. Served in ceramics, never paper, when you stay.',
   110, 100, null, null, null, '{}',
   '{"sizes":[{"label":"8oz","delta":0},{"label":"12oz","delta":25}],"milks":["Whole","Oat","Almond","None"],"addons":[{"label":"Extra shot","price":35},{"label":"Vanilla syrup","price":20},{"label":"Caramel syrup","price":20},{"label":"Cinnamon dust","price":10}],"sugar":true,"notes":"House blend — cocoa · panela · dried fig"}',
   true, true, null),
  ('americano', 'coffee', 'espresso', 'Americano',
   'Long, black, and honest.',
   'Two shots lengthened with hot water. Clean and quiet — the drink we judge the beans by.',
   120, 100, null, null, null, '{}',
   '{"sizes":[{"label":"8oz","delta":0},{"label":"12oz","delta":25}],"milks":["Whole","Oat","Almond","None"],"addons":[{"label":"Extra shot","price":35},{"label":"Vanilla syrup","price":20},{"label":"Caramel syrup","price":20},{"label":"Cinnamon dust","price":10}],"sugar":true,"notes":"House blend — almond · brown sugar"}',
   true, true, null),
  ('cortado', 'coffee', 'espresso', 'Cortado',
   'Equal parts espresso and steamed milk.',
   'A small, no-foam classic. Cut, not covered — for people who want milk as a supporting act.',
   140, 100, null, null, null, '{}',
   '{"sizes":[{"label":"8oz","delta":0},{"label":"12oz","delta":25}],"milks":["Whole","Oat","Almond","None"],"addons":[{"label":"Extra shot","price":35},{"label":"Vanilla syrup","price":20},{"label":"Caramel syrup","price":20},{"label":"Cinnamon dust","price":10}],"sugar":true,"notes":"House blend — hazelnut · caramel"}',
   true, false, null),
  ('cappuccino', 'coffee', 'milk-coffee', 'Cappuccino',
   'Dense foam, decent dusting of cocoa.',
   'The old-school third. Thick microfoam over a double shot, finished with a heavier hand of cocoa than we probably should.',
   150, 100, null, null, null, '{}',
   '{"sizes":[{"label":"8oz","delta":0},{"label":"12oz","delta":25}],"milks":["Whole","Oat","Almond","None"],"addons":[{"label":"Extra shot","price":35},{"label":"Vanilla syrup","price":20},{"label":"Caramel syrup","price":20},{"label":"Cinnamon dust","price":10}],"sugar":true,"notes":"House blend — milk chocolate"}',
   true, true, null),
  ('latte', 'coffee', 'milk-coffee', 'Latte',
   'Silky, simple, done right.',
   'Our default for a reason — a double shot folded into steamed milk, poured with whatever the barista feels like drawing that day.',
   155, 100, null, null, null, '{}',
   '{"sizes":[{"label":"8oz","delta":0},{"label":"12oz","delta":25}],"milks":["Whole","Oat","Almond","None"],"addons":[{"label":"Extra shot","price":35},{"label":"Vanilla syrup","price":20},{"label":"Caramel syrup","price":20},{"label":"Cinnamon dust","price":10}],"sugar":true,"notes":"House blend — butter · graham"}',
   true, false, null),
  ('spanish-latte', 'coffee', 'milk-coffee', 'Spanish Latte',
   'Condensed milk. No apologies.',
   'Sweet, thick, and unreasonably good. Espresso cut with condensed milk and steamed milk — our most-ordered drink two seasons running.',
   165, 100, null, null, null, '{}',
   '{"sizes":[{"label":"8oz","delta":0},{"label":"12oz","delta":25}],"milks":["Whole","Oat","Almond","None"],"addons":[{"label":"Extra shot","price":35},{"label":"Vanilla syrup","price":20},{"label":"Caramel syrup","price":20},{"label":"Cinnamon dust","price":10}],"sugar":true,"notes":"House blend — dulce de leche"}',
   true, true, null),
  ('iced-spanish-latte', 'coffee', 'cold-coffee', 'Iced Spanish Latte',
   'The cold one everyone talks about.',
   'Condensed milk stirred cold with a double shot and poured over big cubes. Comes with our honest recommendation to pair it with denim.',
   170, 100, null, null, null, '{}',
   '{"sizes":[{"label":"8oz","delta":0},{"label":"12oz","delta":25}],"milks":["Whole","Oat","Almond","None"],"addons":[{"label":"Extra shot","price":35},{"label":"Vanilla syrup","price":20},{"label":"Caramel syrup","price":20},{"label":"Cinnamon dust","price":10}],"sugar":true,"notes":"House blend — dulce · vanilla"}',
   true, false, null),
  ('cold-brew', 'coffee', 'cold-coffee', 'Cold Brew',
   'Steeped for 18 hours. Worth all of them.',
   'Coarse-ground single origin steeped overnight, served over ice with a splash of orange peel if you ask nicely. Low acid, high focus.',
   170, 100, null, null, null, '{}',
   '{"sizes":[{"label":"12oz","delta":0},{"label":"16oz","delta":30}],"milks":["None","Oat"],"addons":[{"label":"Extra shot","price":35},{"label":"Vanilla syrup","price":20},{"label":"Caramel syrup","price":20},{"label":"Cinnamon dust","price":10}],"sugar":true,"notes":"Single origin — dark cherry · cacao nib"}',
   true, true, null),
  ('espresso-tonic', 'coffee', 'specialty', 'Espresso Tonic',
   'Bright, bitter, sparkling.',
   'A shot poured over chilled tonic and ice, built against the glass so the crema ribbons. Summer in a highball.',
   180, 100, null, null, null, '{}',
   '{"sizes":[{"label":"10oz","delta":0}],"milks":["None"],"addons":[{"label":"Extra shot","price":35},{"label":"Vanilla syrup","price":20},{"label":"Caramel syrup","price":20},{"label":"Cinnamon dust","price":10}],"sugar":true,"notes":"Ethiopia — citrus · juniper · fizz"}',
   true, false, null),
  ('honey-oat-latte', 'coffee', 'specialty', 'Honey Oat Latte',
   'Local honey, oat milk, warm mug.',
   'Wild honey from Batangas whisked into oat milk and espresso. Comfort structured as a beverage.',
   180, 100, null, null, null, '{}',
   '{"sizes":[{"label":"8oz","delta":0},{"label":"12oz","delta":25}],"milks":["Whole","Oat","Almond","None"],"addons":[{"label":"Extra shot","price":35},{"label":"Vanilla syrup","price":20},{"label":"Caramel syrup","price":20},{"label":"Cinnamon dust","price":10}],"sugar":true,"notes":"Oat · wildflower honey · toast"}',
   true, false, null),
  ('matcha-latte', 'coffee', 'non-coffee', 'Matcha Latte',
   'Ceremonial grade, whisked to order.',
   'Stone-ground ceremonial matcha whisked into a paste, then topped with steamed milk of your choosing. Grassy, sweet, and quietly caffeinated.',
   170, 100, null, null, null, '{}',
   '{"sizes":[{"label":"8oz","delta":0},{"label":"12oz","delta":25}],"milks":["Whole","Oat","Almond","None"],"addons":[{"label":"Extra shot","price":35},{"label":"Vanilla syrup","price":20},{"label":"Caramel syrup","price":20},{"label":"Cinnamon dust","price":10}],"sugar":true,"notes":"Uji, Kyoto — sweet grass · umami"}',
   true, true, null),
  ('iced-chocolate', 'coffee', 'non-coffee', 'Iced Chocolate',
   '70% dark, shaken cold.',
   'Tablea from Davao melted into dark chocolate, shaken with milk and poured over ice. Not a hot chocolate that got cold — its own thing.',
   160, 100, null, null, null, '{}',
   '{"sizes":[{"label":"12oz","delta":0},{"label":"16oz","delta":30}],"milks":["Whole","Oat"],"addons":[{"label":"Extra shot","price":35},{"label":"Vanilla syrup","price":20},{"label":"Caramel syrup","price":20},{"label":"Cinnamon dust","price":10}],"sugar":true,"notes":"Davao tablea — dark cocoa · cherry"}',
   true, false, null),
  ('butter-croissant', 'coffee', 'pastries', 'Butter Croissant',
   'Laminated in-house, baked at 6am.',
   'Twenty-seven layers of butter, folded the night before and baked every morning. Shatters when you look at it.',
   120, 100, null, null, null, '{}',
   '{"sizes":null,"milks":null,"addons":[],"sugar":false}',
   true, true, null),
  ('chocolate-croissant', 'coffee', 'pastries', 'Chocolate Croissant',
   'Same lamination, dark center.',
   'The butter croissant with two batons of 64% dark chocolate rolled inside. Best with an americano, honestly.',
   140, 100, null, null, null, '{}',
   '{"sizes":null,"milks":null,"addons":[],"sugar":false}',
   true, false, null),
  ('banana-bread', 'coffee', 'pastries', 'Banana Bread',
   'Toasted, with salted butter.',
   'Saba banana loaf with walnuts, served toasted with a slick of salted butter. Pairs suspiciously well with the cold brew.',
   110, 100, null, null, null, '{}',
   '{"sizes":null,"milks":null,"addons":[],"sugar":false}',
   true, false, null)
on conflict (slug) do update set
  type = excluded.type, category = excluded.category, name = excluded.name,
  short_desc = excluded.short_desc, description = excluded.description,
  price = excluded.price, stock = excluded.stock, brand = excluded.brand,
  size = excluded.size, condition_grade = excluded.condition_grade,
  measurements = excluded.measurements, options = excluded.options,
  is_available = excluded.is_available, is_featured = excluded.is_featured,
  collection = excluded.collection;

-- ============ THRIFT (14) ============
insert into public.products
  (slug, type, category, name, short_desc, description, price, stock,
   brand, size, condition_grade, measurements, options,
   is_available, is_featured, collection)
values
  ('vintage-denim-jacket', 'thrift', 'denim', 'Vintage Denim Jacket',
   'Broken-in trucker cut from the 90s. Faded exactly where you want it.',
   'A proper 90s trucker — copper hardware, worn fades at the elbows, and a fit that sits just right over a hoodie or a tee. Broken in by someone else so you can skip the ten-year wait.',
   850, 1, 'Levi''s', 'L', 9,
   '{"Chest": "22\"","Length": "25.5\"","Shoulders": "18\"","Sleeve": "24\""}', '{}',
   true, true, 'drop-04'),
  ('workwear-jacket', 'thrift', 'outerwear', 'Workwear Jacket',
   'Duck canvas chore coat, softened by real years of work.',
   'The good kind of beat. Duck canvas gone soft in the right places, tool pockets deep enough to be useful, and a blanket lining for cold mornings on the motorbike.',
   1450, 1, 'Carhartt', 'M', 8,
   '{"Chest": "21\"","Length": "26\"","Shoulders": "17.5\"","Sleeve": "23.5\""}', '{}',
   true, true, 'drop-04'),
  ('vintage-polo', 'thrift', 'tops', 'Vintage Polo',
   'Piqué cotton, small pony, big energy.',
   'A proper piqué polo from when they were built to last. No shrinking, no pilling, collar that still stands on its own.',
   550, 1, 'Lacoste', 'M', 9,
   '{"Chest": "20\"","Length": "26\"","Shoulders": "17\""}', '{}',
   true, true, null),
  ('graphic-tee', 'thrift', 'tops', 'Graphic Tee',
   'Single-stitch bootleg print, cracked in the best way.',
   'Single-stitch body, huge faded print, hem that has been rolled a thousand times. The kind of tee that starts conversations in line for coffee.',
   380, 1, '90s Bootleg', 'L', 8,
   '{"Chest": "21\"","Length": "27\"","Shoulders": "18.5\""}', '{}',
   true, true, 'drop-04'),
  ('cargo-pants', 'thrift', 'bottoms', 'Cargo Pants',
   'Fatigues with honest fade and deep bellows pockets.',
   'Work-cut cargos with a straight leg and real bellows pockets. Worn to softness, never to failure — Dickies in this condition is a quiet flex.',
   720, 1, 'Dickies', '32', 8,
   '{"Waist": "16\"","Inseam": "30\"","Rise": "12\""}', '{}',
   true, true, null),
  ('vintage-levis-501', 'thrift', 'denim', 'Vintage Levi''s 501',
   'Made-in-USA 501s with honeycomb fade intact.',
   'Red tab, button fly, honeycombs behind the knees. Straight-cut 501s from the golden era — the pair thrift folklore is written about.',
   1250, 1, 'Levi''s', '30', 9,
   '{"Waist": "15.5\"","Inseam": "30\"","Rise": "11.5\"","Leg": "8\""}', '{}',
   true, true, 'drop-04'),
  ('canvas-tote', 'thrift', 'accessories', 'Canvas Tote',
   'Heavy duck canvas, market-day proven.',
   'A carry-all with a past — canvas worn smooth, handles re-stitched by hand somewhere along the way. Fits a laptop, a novel, and a bag of beans.',
   280, 1, 'Vintage Unbranded', 'OS', 8,
   '{"Width": "15\"","Height": "16\"","Strap": "10\""}', '{}',
   true, true, null),
  ('vintage-sneakers', 'thrift', 'footwear', 'Vintage Sneakers',
   'Suede runners from another decade, gently scuffed.',
   'Suede and mesh runners with honest creasing and a story in every scuff. Cleaned, deodorized, and resoled at the heel — ready for their next decade.',
   950, 1, 'Nike', '9US', 7,
   '{"Insole": "10.5\"","Width": "3.8\""}', '{}',
   true, true, null),
  ('corduroy-shirt', 'thrift', 'tops', 'Corduroy Shirt',
   'Wide-wale cord, pearl snaps, western cut.',
   'Wide-wale corduroy with pearl snap buttons and a pointed yoke. Worn soft like a favorite armchair.',
   520, 1, 'Wrangler', 'M', 9,
   '{"Chest": "21\"","Length": "27\"","Sleeve": "24\""}', '{}',
   true, false, null),
  ('pleated-trousers', 'thrift', 'bottoms', 'Pleated Trousers',
   'Double-pleat wool blend that drapes like a dream.',
   'Double pleats, high rise, and a drape that cheap trousers will never learn. Wool blend that breathes through summer.',
   480, 1, 'Vintage Unbranded', 'S', 9,
   '{"Waist": "14\"","Inseam": "28\"","Rise": "12.5\""}', '{}',
   true, false, null),
  ('fleece-jacket', 'thrift', 'outerwear', 'Fleece Jacket',
   'Retro pile fleece — sold before we could even tag it.',
   'The one that got away. Retro pile fleece with a full zip and a color you cannot reproduce. We keep the listing up so you can feel the loss too.',
   1100, 0, 'Patagonia', 'M', 8,
   '{"Chest": "21\"","Length": "25\"","Sleeve": "23\""}', '{}',
   false, false, null),
  ('silk-scarf', 'thrift', 'accessories', 'Silk Scarf',
   'Hand-rolled edges, printed border, countless ways to wear it.',
   'A printed silk square with hand-rolled edges. Neck, wrist, handlebars, hair — four accessories in one.',
   320, 1, 'Vintage Unbranded', 'OS', 9,
   '{"Size": "26\" × 26\""}', '{}',
   true, false, null),
  ('checkerboard-vans', 'thrift', 'footwear', 'Checkerboard Vans',
   'Classic checkers, skated exactly as intended.',
   'Checkerboard slip-ons worn the way they were designed to be worn. Sold to a good home — watch the next drop for more.',
   850, 0, 'Vans', '8US', 7,
   '{"Insole": "9.8\"","Width": "3.6\""}', '{}',
   false, false, null),
  ('chore-coat', 'thrift', 'outerwear', 'Chore Coat',
   'French moleskin work jacket with three forgiving pockets.',
   'Moleskin cotton workwear from a French farm co-op, sun-faded to a warm ecru. Three pockets, one button missing replaced with vintage stock.',
   980, 1, 'Vintage French', 'L', 8,
   '{"Chest": "22.5\"","Length": "27\"","Shoulders": "19\"","Sleeve": "24.5\""}', '{}',
   true, false, null)
on conflict (slug) do update set
  type = excluded.type, category = excluded.category, name = excluded.name,
  short_desc = excluded.short_desc, description = excluded.description,
  price = excluded.price, stock = excluded.stock, brand = excluded.brand,
  size = excluded.size, condition_grade = excluded.condition_grade,
  measurements = excluded.measurements, options = excluded.options,
  is_available = excluded.is_available, is_featured = excluded.is_featured,
  collection = excluded.collection;

-- ============ PRODUCT IMAGES (29) ============
-- Same photo URLs the static data uses today; re-run safe.
insert into public.product_images (product_id, url, sort)
select p.id, v.url, 0
from public.products p
join (values
  ('espresso', 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=600&q=80'),
  ('americano', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80'),
  ('cortado', 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&q=80'),
  ('cappuccino', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=80'),
  ('latte', 'https://images.unsplash.com/photo-1541167760496-1628856ab772?w=600&q=80'),
  ('spanish-latte', 'https://images.unsplash.com/photo-1522992319-0365e5f11656?w=600&q=80'),
  ('iced-spanish-latte', 'https://images.unsplash.com/photo-1517959105821-eaf2591984ca?w=600&q=80'),
  ('cold-brew', 'https://images.unsplash.com/photo-1553909489-cd47e0907980?w=600&q=80'),
  ('espresso-tonic', 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&q=80'),
  ('honey-oat-latte', 'https://images.unsplash.com/photo-1512568400610-62da28bc8a13?w=600&q=80'),
  ('matcha-latte', 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&q=80'),
  ('iced-chocolate', 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=600&q=80'),
  ('butter-croissant', 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80'),
  ('chocolate-croissant', 'https://images.unsplash.com/photo-1623334044303-241021148842?w=600&q=80'),
  ('banana-bread', 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=600&q=80'),
  ('vintage-denim-jacket', 'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600&q=80'),
  ('workwear-jacket', 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80'),
  ('vintage-polo', 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&q=80'),
  ('graphic-tee', 'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=600&q=80'),
  ('cargo-pants', 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80'),
  ('vintage-levis-501', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80'),
  ('canvas-tote', 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&q=80'),
  ('vintage-sneakers', 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80'),
  ('corduroy-shirt', 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80'),
  ('pleated-trousers', 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80'),
  ('fleece-jacket', 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&q=80'),
  ('silk-scarf', 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&q=80'),
  ('checkerboard-vans', 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&q=80'),
  ('chore-coat', 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80')
) as v(slug, url) on p.slug = v.slug
where not exists (
  select 1 from public.product_images pi where pi.product_id = p.id
);

-- ============ EVENTS (7) ============
insert into public.events (slug, title, description, date, time, slots, status, image)
values
  ('thrift-drop-04', 'THRIFT DROP 04',
   'Forty new one-of-one pieces go live in-store and online. First come, first kept — doors at 7, espresso bar stays open late.',
   '2026-09-11', '7:00 PM', '40 pieces', 'upcoming',
   'https://images.unsplash.com/photo-1489987707025-afc232f7bdaf?w=800&q=80'),
  ('live-dj-night', 'LIVE DJ NIGHT',
   'Vinyl-only sets from residents Blandine and Kuya Aero. Disco, city pop, and quiet-storm between clothing racks.',
   '2026-09-19', '8:00 PM', '80 slots', 'upcoming',
   'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80'),
  ('coffee-workshop-pour-over', 'COFFEE WORKSHOP — POUR OVER BASICS',
   'Ninety minutes on grind size, water, and patience. Take home a bag of the beans you brewed and a lifetime of opinions about kettles.',
   '2026-09-26', '2:00 PM', '12 slots', 'upcoming',
   'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80'),
  ('popup-market', 'POP-UP MARKET',
   'Local makers take over the parking lot — ceramics, prints, plants, and vintage dealers we personally vouch for.',
   '2026-10-03', '10:00 AM', 'Free entry', 'upcoming',
   'https://images.unsplash.com/photo-1481437156560-3205f6a55735?w=800&q=80'),
  ('clothing-swap', 'CLOTHING SWAP',
   'Bring three pieces you are done with, take home someone else''s future favorite. Leftovers go to our donation partner.',
   '2026-10-10', '1:00 PM', '60 slots', 'upcoming',
   'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800&q=80'),
  ('acoustic-session', 'ACOUSTIC SESSION',
   'Two guitars, one cajón, and a setlist of OPM deep cuts. The night we ran out of cold brew by 9pm.',
   '2026-08-29', '7:30 PM', 'Waitlist only', 'past',
   'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800&q=80'),
  ('denim-repair-workshop', 'DENIM REPAIR WORKSHOP',
   'Visible mending 101 — sashiko patches, iron-on art, and the philosophy of wearing your repairs proudly.',
   '2026-07-18', '2:00 PM', 'Sold out', 'past',
   'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&q=80')
on conflict (slug) do update set
  title = excluded.title, description = excluded.description, date = excluded.date,
  time = excluded.time, slots = excluded.slots, status = excluded.status,
  image = excluded.image;

-- ============ VERIFY ============
-- Expect: 29 products, 29 images, 7 events.
select 'products' as tbl, count(*) as n from public.products
union all select 'product_images', count(*) from public.product_images
union all select 'events', count(*) from public.events;
